[package]
name = "sheetz"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
arboard = "3.6.1"
eframe = "0.33.3"
ironcalc = "0.8.3"
rfd = "0.17.2"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = { version = "1.0.151", features = ["preserve_order"] }
toml = "1.1.4"
