/// Every user-invocable action has a stable string id. `keymap.toml` binds key
/// chords to these ids; menu entries dispatch the same commands.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum Command {
    MoveUp,
    MoveDown,
    MoveLeft,
    MoveRight,
    ExtendUp,
    ExtendDown,
    ExtendLeft,
    ExtendRight,
    JumpUp,
    JumpDown,
    JumpLeft,
    JumpRight,
    PageUp,
    PageDown,
    Home,
    HomeAll,
    EndData,
    EditCell,
    Clear,
    FillDown,
    FillRight,
    Undo,
    Redo,
    Copy,
    Cut,
    Paste,
    SelectAll,
    New,
    Open,
    Save,
    SaveAs,
    NextSheet,
    PrevSheet,
    NewSheet,
    Quit,
}

impl Command {
    pub fn from_id(id: &str) -> Option<Command> {
        use Command::*;
        Some(match id {
            "move_up" => MoveUp,
            "move_down" => MoveDown,
            "move_left" => MoveLeft,
            "move_right" => MoveRight,
            "extend_up" => ExtendUp,
            "extend_down" => ExtendDown,
            "extend_left" => ExtendLeft,
            "extend_right" => ExtendRight,
            "jump_up" => JumpUp,
            "jump_down" => JumpDown,
            "jump_left" => JumpLeft,
            "jump_right" => JumpRight,
            "page_up" => PageUp,
            "page_down" => PageDown,
            "home" => Home,
            "home_all" => HomeAll,
            "end_data" => EndData,
            "edit_cell" => EditCell,
            "clear" => Clear,
            "fill_down" => FillDown,
            "fill_right" => FillRight,
            "undo" => Undo,
            "redo" => Redo,
            "copy" => Copy,
            "cut" => Cut,
            "paste" => Paste,
            "select_all" => SelectAll,
            "new" => New,
            "open" => Open,
            "save" => Save,
            "save_as" => SaveAs,
            "next_sheet" => NextSheet,
            "prev_sheet" => PrevSheet,
            "new_sheet" => NewSheet,
            "quit" => Quit,
            _ => return None,
        })
    }
}
