/// Every user-invocable action has a stable string id. `keymap.toml` binds key
/// chords to these ids; ribbon buttons and menus dispatch the same commands.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum Command {
    // Navigation
    MoveUp,
    MoveDown,
    MoveLeft,
    MoveRight,
    ExtendUp,
    ExtendDown,
    ExtendLeft,
    ExtendRight,
    JumpUp,
    JumpDown,
    JumpLeft,
    JumpRight,
    ExtendJumpUp,
    ExtendJumpDown,
    ExtendJumpLeft,
    ExtendJumpRight,
    PageUp,
    PageDown,
    Home,
    HomeAll,
    EndData,
    GotoCell,

    // Selection
    SelectAll,
    SelectRow,
    SelectColumn,

    // Editing
    EditCell,
    Clear,
    ClearFormats,
    ClearAll,
    FillDown,
    FillRight,
    Undo,
    Redo,
    Copy,
    Cut,
    Paste,
    PasteValues,

    // Formatting
    ToggleBold,
    ToggleItalic,
    ToggleUnderline,
    ToggleStrike,
    AlignLeft,
    AlignCenter,
    AlignRight,
    ToggleWrap,
    IncreaseFont,
    DecreaseFont,
    BorderAll,
    BorderOuter,
    BorderBottom,
    BorderNone,
    FormatGeneral,
    FormatNumber,
    FormatCurrency,
    FormatPercent,
    FormatComma,
    FormatDate,
    IncreaseDecimal,
    DecreaseDecimal,
    FormatDialog,

    // Structure
    InsertRow,
    InsertColumn,
    DeleteRow,
    DeleteColumn,
    AutofitColumn,

    // Data
    FindReplace,
    FindNext,
    FindPrev,
    SortAscending,
    SortDescending,
    ToggleFilter,
    NameManager,
    ConditionalFormat,
    InsertChart,

    // View
    FreezePanes,
    FreezeTopRow,
    FreezeFirstColumn,
    Unfreeze,
    ToggleGridLines,
    ZoomIn,
    ZoomOut,
    ZoomReset,

    // File
    New,
    Open,
    Save,
    SaveAs,
    Quit,

    // Sheets
    NextSheet,
    PrevSheet,
    NewSheet,
    RenameSheet,
    DeleteSheet,
    DuplicateSheet,
    MoveSheetLeft,
    MoveSheetRight,

    // Help
    ShortcutHelp,
}

impl Command {
    pub fn from_id(id: &str) -> Option<Command> {
        use Command::*;
        Some(match id {
            "move_up" => MoveUp,
            "move_down" => MoveDown,
            "move_left" => MoveLeft,
            "move_right" => MoveRight,
            "extend_up" => ExtendUp,
            "extend_down" => ExtendDown,
            "extend_left" => ExtendLeft,
            "extend_right" => ExtendRight,
            "jump_up" => JumpUp,
            "jump_down" => JumpDown,
            "jump_left" => JumpLeft,
            "jump_right" => JumpRight,
            "extend_jump_up" => ExtendJumpUp,
            "extend_jump_down" => ExtendJumpDown,
            "extend_jump_left" => ExtendJumpLeft,
            "extend_jump_right" => ExtendJumpRight,
            "page_up" => PageUp,
            "page_down" => PageDown,
            "home" => Home,
            "home_all" => HomeAll,
            "end_data" => EndData,
            "goto_cell" => GotoCell,
            "select_all" => SelectAll,
            "select_row" => SelectRow,
            "select_column" => SelectColumn,
            "edit_cell" => EditCell,
            "clear" => Clear,
            "clear_formats" => ClearFormats,
            "clear_all" => ClearAll,
            "fill_down" => FillDown,
            "fill_right" => FillRight,
            "undo" => Undo,
            "redo" => Redo,
            "copy" => Copy,
            "cut" => Cut,
            "paste" => Paste,
            "paste_values" => PasteValues,
            "bold" => ToggleBold,
            "italic" => ToggleItalic,
            "underline" => ToggleUnderline,
            "strike" => ToggleStrike,
            "align_left" => AlignLeft,
            "align_center" => AlignCenter,
            "align_right" => AlignRight,
            "wrap_text" => ToggleWrap,
            "increase_font" => IncreaseFont,
            "decrease_font" => DecreaseFont,
            "border_all" => BorderAll,
            "border_outer" => BorderOuter,
            "border_bottom" => BorderBottom,
            "border_none" => BorderNone,
            "format_general" => FormatGeneral,
            "format_number" => FormatNumber,
            "format_currency" => FormatCurrency,
            "format_percent" => FormatPercent,
            "format_comma" => FormatComma,
            "format_date" => FormatDate,
            "increase_decimal" => IncreaseDecimal,
            "decrease_decimal" => DecreaseDecimal,
            "format_dialog" => FormatDialog,
            "insert_row" => InsertRow,
            "insert_column" => InsertColumn,
            "delete_row" => DeleteRow,
            "delete_column" => DeleteColumn,
            "autofit_column" => AutofitColumn,
            "find_replace" => FindReplace,
            "find_next" => FindNext,
            "find_prev" => FindPrev,
            "sort_ascending" => SortAscending,
            "sort_descending" => SortDescending,
            "toggle_filter" => ToggleFilter,
            "name_manager" => NameManager,
            "conditional_format" => ConditionalFormat,
            "insert_chart" => InsertChart,
            "freeze_panes" => FreezePanes,
            "freeze_top_row" => FreezeTopRow,
            "freeze_first_column" => FreezeFirstColumn,
            "unfreeze" => Unfreeze,
            "toggle_grid_lines" => ToggleGridLines,
            "zoom_in" => ZoomIn,
            "zoom_out" => ZoomOut,
            "zoom_reset" => ZoomReset,
            "new" => New,
            "open" => Open,
            "save" => Save,
            "save_as" => SaveAs,
            "quit" => Quit,
            "next_sheet" => NextSheet,
            "prev_sheet" => PrevSheet,
            "new_sheet" => NewSheet,
            "rename_sheet" => RenameSheet,
            "delete_sheet" => DeleteSheet,
            "duplicate_sheet" => DuplicateSheet,
            "move_sheet_left" => MoveSheetLeft,
            "move_sheet_right" => MoveSheetRight,
            "shortcut_help" => ShortcutHelp,
            _ => return None,
        })
    }

    /// Human-readable name, used by the shortcut help window.
    pub fn label(self) -> &'static str {
        use Command::*;
        match self {
            MoveUp => "Move up",
            MoveDown => "Move down",
            MoveLeft => "Move left",
            MoveRight => "Move right",
            ExtendUp => "Extend selection up",
            ExtendDown => "Extend selection down",
            ExtendLeft => "Extend selection left",
            ExtendRight => "Extend selection right",
            JumpUp => "Jump to edge up",
            JumpDown => "Jump to edge down",
            JumpLeft => "Jump to edge left",
            JumpRight => "Jump to edge right",
            ExtendJumpUp => "Extend to edge up",
            ExtendJumpDown => "Extend to edge down",
            ExtendJumpLeft => "Extend to edge left",
            ExtendJumpRight => "Extend to edge right",
            PageUp => "Page up",
            PageDown => "Page down",
            Home => "Start of row",
            HomeAll => "Start of sheet",
            EndData => "End of data",
            GotoCell => "Go to cell",
            SelectAll => "Select all",
            SelectRow => "Select row",
            SelectColumn => "Select column",
            EditCell => "Edit cell",
            Clear => "Clear contents",
            ClearFormats => "Clear formatting",
            ClearAll => "Clear all",
            FillDown => "Fill down",
            FillRight => "Fill right",
            Undo => "Undo",
            Redo => "Redo",
            Copy => "Copy",
            Cut => "Cut",
            Paste => "Paste",
            PasteValues => "Paste values only",
            ToggleBold => "Bold",
            ToggleItalic => "Italic",
            ToggleUnderline => "Underline",
            ToggleStrike => "Strikethrough",
            AlignLeft => "Align left",
            AlignCenter => "Align center",
            AlignRight => "Align right",
            ToggleWrap => "Wrap text",
            IncreaseFont => "Increase font size",
            DecreaseFont => "Decrease font size",
            BorderAll => "All borders",
            BorderOuter => "Outside borders",
            BorderBottom => "Bottom border",
            BorderNone => "No borders",
            FormatGeneral => "General format",
            FormatNumber => "Number format",
            FormatCurrency => "Currency format",
            FormatPercent => "Percent format",
            FormatComma => "Comma format",
            FormatDate => "Date format",
            IncreaseDecimal => "Increase decimals",
            DecreaseDecimal => "Decrease decimals",
            FormatDialog => "Format cells…",
            InsertRow => "Insert row",
            InsertColumn => "Insert column",
            DeleteRow => "Delete row",
            DeleteColumn => "Delete column",
            AutofitColumn => "Autofit column width",
            FindReplace => "Find & Replace",
            FindNext => "Find next",
            FindPrev => "Find previous",
            SortAscending => "Sort ascending",
            SortDescending => "Sort descending",
            ToggleFilter => "Toggle filter",
            NameManager => "Name manager",
            ConditionalFormat => "Conditional formatting",
            InsertChart => "Insert chart",
            FreezePanes => "Freeze panes",
            FreezeTopRow => "Freeze top row",
            FreezeFirstColumn => "Freeze first column",
            Unfreeze => "Unfreeze panes",
            ToggleGridLines => "Toggle grid lines",
            ZoomIn => "Zoom in",
            ZoomOut => "Zoom out",
            ZoomReset => "Reset zoom",
            New => "New workbook",
            Open => "Open workbook",
            Save => "Save",
            SaveAs => "Save as",
            Quit => "Quit",
            NextSheet => "Next sheet",
            PrevSheet => "Previous sheet",
            NewSheet => "New sheet",
            RenameSheet => "Rename sheet",
            DeleteSheet => "Delete sheet",
            DuplicateSheet => "Duplicate sheet",
            MoveSheetLeft => "Move sheet left",
            MoveSheetRight => "Move sheet right",
            ShortcutHelp => "Keyboard shortcuts",
        }
    }
}
